name: Go presubmit checks
author: M. J. Fromberger
description: Run Go tests and static checks

branding:
  icon: eye
  color: green

inputs:
  staticcheck-version:
    description: "Version of staticcheck to use"
    required: false
    default: "latest"

  go-test-cpu:
    description: "Comma-separated list of CPU combinations for the Go race detector"
    required: false
    default: "1,2"

  go-proxy:
    description: "The URL of the Go module proxy to use, or 'direct' to bypass"
    required: false
    default: "https://proxy.golang.org"

  check-staticcheck:
    description: "Run staticcheck over the module"
    required: false
    default: "yes"

  check-replace:
    description: "Check for replace directives in the go.mod file"
    required: false
    default: "yes"

runs:
  using: composite
  steps:
    - name: Run presubmit checks
      shell: bash
      env:
        GO_TEST_CPU: ${{ inputs.go-test-cpu }}
        GOPROXY: ${{ inputs.go-proxy }}
        CHECK_STATICCHECK: ${{ inputs.check-staticcheck }}
        CHECK_REPLACE: ${{ inputs.check-replace }}
        STATICCHECK_VERSION: ${{ inputs.staticcheck-version }}
      run: $GITHUB_ACTION_PATH/check.sh
