name: Go presubmit checks
author: M. J. Fromberger
description: Run Go tests and static checks

branding:
  icon: eye
  color: green

inputs:
  staticcheck-version:
    description: "Version of staticcheck to use"
    required: false
    default: "2020.2"

  go-test-cpu:
    description: "Comma-separated list of CPU combinations for the Go race detector"
    required: false
    default: "1,2"

  go-proxy:
    description: "The URL of the Go module proxy to use, or 'direct' to bypass"
    required: false
    default: "https://proxy.golang.org"

runs:
  using: composite
  steps:
    - name: Install staticcheck
      shell: bash
      env:
        GO111MODULE: on
        GOPROXY: ${{ inputs.go-proxy }}
        STATICCHECK_VERSION: ${{ inputs.staticcheck-version }}
      run: $GITHUB_ACTION_PATH/install.sh

    - name: Run presubmit checks
      shell: bash
      env:
        GO_TEST_CPU: ${{ inputs.go-test-cpu }}
        GOPROXY: ${{ inputs.go-proxy }}
      run: $GITHUB_ACTION_PATH/check.sh
