name: Go presubmit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Go presubmit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.16', '1.17']
        os: ['ubuntu-latest', 'macos-latest']
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - uses: creachadair/go-presubmit-action@default
