name: Go presubmit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: Go presubmit
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: creachadair/go-presubmit-action@v2
